### ISSUE TITLE
Error "(UndefinedFunctionError) function Ecto.Adapters.Postgres.load/2 is undefined or private"

### ISSUE THREAD

**Issue by acrolink** [cometaworks/fast_fuzzy_search_in_phoenix_and_ecto#5]
I get the above mentioned error when using `Ecto.execute_and_load(..)`. I simply don't understand why it must be so hard to execute simple SQL query and show the results in a view template. I simply need to execute a SELECT query and display the rows in a HTML table.

**Comment by ybur-yug** [comment]
@acrolink this is for a very precise problem: A fuzzy search on a text column that is 255 characters or less. You do not need to do anything this wild for a simple `SELECT`. Check out the [Ecto.Query docs](https://hexdocs.pm/ecto/Ecto.Query.html).
